Parameters:
  SecurityGroupDescription1:
    Description: Security Group Description
    Type: String

  SecurityGroupDescription2:
    Description: Security Group Description
    Type: String

Resources:
  MyInstance:
    # Type: AWS::{aws-product-name}::{data-type-name}
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-038f1ca1bd58a5790
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroupSSH
        - !Ref SecurityGroupServer

  # an elastic IP attached for our instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance # Associated instance ID (E.g. i-08424206ddf7cde90)

  # our first EC2 security group
  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup # Define the physical resource
    Properties:
      GroupDescription: !Ref SecurityGroupDescription1
      SecurityGroupIngress:
        - IpProtocol: tcp # Protocol
          FromPort: 22 # Port range
          ToPort: 22 # Port range
          CidrIp: 0.0.0.0/0 # Source

  # our second EC2 security group
  SecurityGroupServer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 192.168.1.1/32
